server:
  port: 8084
  context-path: /carPlateform

spring:
  application:
    name: caranalysis
  thymeleaf:
    prefix: classpath:/templates/
mybatis:
  mapper-locations: "classpath*:mybatis/*.xml"
  configuration:
    mapUnderscoreToCamelCase: true

logging:
  level:
    com.zld.mapper : debug

messageConfig:
  messageSign: \u3010\u667a\u6167\u505c\u8f66\u4e91\u3011

memcache:
  servers: 127.0.0.1:11211
  failover: true
  initConn: 100
  minConn: 20
  maxConn: 1000
  maintSleep: 50
  nagel: false
  socketTO: 3000
  aliveCheck: true
